# Generated by Django 4.2.2 on 2023-07-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(max_length=100),
        ),
    ]
