# Generated by Django 4.2.2 on 2023-07-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_message1_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message1',
            name='timestamp',
        ),
    ]
